### ISSUE TITLE
A great plugin, I am very worried about the compatibility of your plugin with other plugins (such as Residence)

### ISSUE THREAD

**Issue by Dazzle-sys** [lokka30/PhantomWorlds#21]
A great plugin, I am very worried about the compatibility of your plugin with other plugins (such as Residence)

**Comment by lokka30** [comment]
> 
> 
> A great plugin, I am very worried about the compatibility of your plugin with other plugins (such as Residence)

Thanks! I haven't heard of any issues with Residence, and it is a premium plugin so I can't test it myself. I don't see where they could be incompatible. How come are you worried about pairing the two?

**Comment by lokka30** [comment]
Closing this issue; half a month of inactivity.
