### ISSUE TITLE
Does PhantomWorlds have an idea to replace Multiverse-Core?

### ISSUE THREAD

**Issue by Dazzle-sys** [lokka30/PhantomWorlds#25]
If you don’t have the idea of replacing Multiverse-Core, then I don’t know what special features of PhantomWorlds can attract me

**Comment by lokka30** [comment]
Hi, it depends on your needs. I've stated all the features of PhantomWorlds on the SpigotMC description page. It does not replace all Multiverse-Core features, although it is very stable and does not seem to have any bugs at all.
