### ISSUE TITLE
Make update checker error more understandable

### ISSUE THREAD

**Issue by lokka30** [lokka30/PhantomWorlds#31]
See [this image](https://cdn.discordapp.com/attachments/803400020715110400/889994391144529960/unknown.png). Catch the exception and just send a warning that PW couldn't check for updates.

It's kind-of a bug, kind-of an enhancement. I've included both labels just to cause extra confusion. 😈

**Comment by awydini** [comment]
Hi,
May I work on this issue?

**Comment by lokka30** [comment]
> 
> 
> Hi, May I work on this issue?

If you wish, you may. This should be easy. Thanks :)
To accomplish this:
* we need to add a `try`/`catch` around the update checker method
* the exception being caught is `java.net.ConnectException`
* In the catch block, get the logger from the `Utils` class (`Utils.LOGGER` if I remember correctly), run `MicroLogger#warning("PhantomWorlds was unable to check for updates, likely due to an unsuitable internet connection.")`

This should do the trick :)

Please let me know if you need any help. Thanks so much! I'll make sure I attribute your contribution fully.

**Comment by awydini** [comment]
Thanks for helping.
I'll do that ;)
